### PR TITLE
add step in iso workflow to remove unused software

### PR DESCRIPTION
**Pull request by BobyMCbobs**
free up space as some builds require having as much space as possible

### CODE REVIEW

**Review by KyleGospo — APPROVED** [review]

**Comment by noelmiller** [comment]
This is likely going to get overwritten with https://github.com/ublue-os/isogenerator/pull/7

I would wait until #7 is merged.

**Comment by JasonN3** [comment]
This wouldn't work in the workflow. The entire job runs inside of a container. The cleanup script would need to run on the container host. There are some ways to work around that, but it's either ugly in the workflow or bad security practice. So far, there has been enough space to build the ISOs since the container only needs to be downloaded once unlike when the containers are being built, which is a completely separate process.
The only reason it works in the current version of the workflow is because the entire workflow was ripped out and replaced with a `docker run` command. That is being changed back in the PR Noel mentioned.

**Comment by BobyMCbobs** [comment]
Thank you for taking a look.
I've just given it a go at
https://github.com/ii/image/commit/91869228a3cc9985450c9b0e39128b8518a41179
and the build ISO job ran successfully
https://github.com/ii/image/actions/runs/7967193605/job/21749605247#step:4:648

I'm unsure how images like Bazzite would build without it given it's size, so I think it's important however it's implementation. Let me know if I can help!

**Comment by JasonN3** [comment]
I just tested building bazzite (https://github.com/ublue-os/isogenerator/actions/runs/7974763018). It did end up failing from lack of space. I added in some lines to my PR (https://github.com/ublue-os/isogenerator/pull/7/commits/ea1a7c96239f8f189389b54c2beb87cedc1f7634) to create some extra space using pretty much the same commands but adjusted to handle not running on the actual host. It will require the container to have the host mounted at /host, which is not good security, but the VM gets recreated for each run, so not a big deal if something happens to the host. I also left it as optional to have that mounted since most of the builds won't need it.

**Comment by BobyMCbobs** [comment]
closing since kinda covered in #7

**Pull request closed without merging**
