### PR TITLE
feat: add creation of sha256 checksum

### LINKED ISSUE #29: Generate and publish signatures
Can we have it also generate shasums so people can check the integrity of each ISO?

### PR DESCRIPTION
**Pull request by noelmiller**
# Purpose

There is a desire by the team to include a sha256 checksum with every creation of an ISO.

Closes https://github.com/ublue-os/isogenerator/issues/29

# What I did

Added bash command to create sha256 checksum after ISO creation is completed

# Tests

Feel free to review build artifacts of recently completed Build ISO tests to validate function.

### CODE REVIEW

**Comment by bsherman** [comment]
Am I missing something? I don't see the sha256 checksum files in artifacts on test ISO workflow.

**Comment by noelmiller** [comment]
> Am I missing something? I don't see the sha256 checksum files in artifacts on test ISO workflow.

The artifact is downloaded as a zip file. I should probably rename that to .zip at this point.

**Review by castrojo — APPROVED** [review]

**Comment by bsherman** [comment]
> > Am I missing something? I don't see the sha256 checksum files in artifacts on test ISO workflow.
> 
> The artifact is downloaded as a zip file. I should probably rename that to .zip at this point.

I don't see a zip file either.  just ISO files

**Comment by noelmiller** [comment]
> > > Am I missing something? I don't see the sha256 checksum files in artifacts on test ISO workflow.
> > 
> > 
> > The artifact is downloaded as a zip file. I should probably rename that to .zip at this point.
> 
> I don't see a zip file either. just ISO files

Click on one of the artifacts in this page and download it. it will download it as a .zip file: https://github.com/ublue-os/isogenerator/actions/runs/8026385034?pr=30

I'll fix the name of the file in a different PR to avoid confusion.

**Comment by bsherman** [comment]
Ok, downloaded the `*.iso` artifact which is actually a ZIP :-)   and within i found both the iso and the checksum file.

and...

```
$ sha256sum -c base-main-38-CHECKSUM
base-main-38.iso: OK
```

**Review by bsherman — APPROVED** [review]

**Pull request merged**
